# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="datajob",
    version="0.1.0",
    python_requires="==3.*,>=3.7.0",
    author="vincent",
    author_email="vclaes1986@gmail.com",
    license="apache-2.0",
    entry_points={"console_scripts": ["datajob = datajob.datajob:run"]},
    packages=["datajob", "datajob.glue", "datajob.package"],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        "aws-cdk.aws-glue==1.*,>=1.70.0",
        "aws-cdk.aws-s3-deployment==1.*,>=1.70.0",
        "aws-cdk.core==1.*,>=1.70.0",
        "aws-empty-bucket==2.*,>=2.4.0",
        "contextvars==2.*,>=2.4.0",
        "dephell==0.*,>=0.8.3",
        "stepfunctions==1.*,>=1.1.2",
        "typer==0.*,>=0.3.2",
    ],
    extras_require={"dev": ["mock==4.*,>=4.0.2", "moto==1.*,>=1.3.16"]},
)
